#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorimeterDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ColorimeterDB")]
	public partial class ColorimeterDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertERP(ERP instance);
    partial void UpdateERP(ERP instance);
    partial void DeleteERP(ERP instance);
    partial void InsertParameter(Parameter instance);
    partial void UpdateParameter(Parameter instance);
    partial void DeleteParameter(Parameter instance);
    partial void InsertPassStd(PassStd instance);
    partial void UpdatePassStd(PassStd instance);
    partial void DeletePassStd(PassStd instance);
    partial void InsertRealTimeProduction(RealTimeProduction instance);
    partial void UpdateRealTimeProduction(RealTimeProduction instance);
    partial void DeleteRealTimeProduction(RealTimeProduction instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertStatisticsProduction(StatisticsProduction instance);
    partial void UpdateStatisticsProduction(StatisticsProduction instance);
    partial void DeleteStatisticsProduction(StatisticsProduction instance);
    #endregion
		
		public ColorimeterDBDataContext() : 
				base(global::ColorimeterDAO.Properties.Settings.Default.ColorimeterDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ColorimeterDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorimeterDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorimeterDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ColorimeterDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ERP> ERP
		{
			get
			{
				return this.GetTable<ERP>();
			}
		}
		
		public System.Data.Linq.Table<Parameter> Parameter
		{
			get
			{
				return this.GetTable<Parameter>();
			}
		}
		
		public System.Data.Linq.Table<PassStd> PassStd
		{
			get
			{
				return this.GetTable<PassStd>();
			}
		}
		
		public System.Data.Linq.Table<RealTimeProduction> RealTimeProduction
		{
			get
			{
				return this.GetTable<RealTimeProduction>();
			}
		}
		
		public System.Data.Linq.Table<User> User
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<StatisticsProduction> StatisticsProduction
		{
			get
			{
				return this.GetTable<StatisticsProduction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP")]
	public partial class ERP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _COLDCOILNO;
		
		private System.Nullable<decimal> _ORDTHK;
		
		private System.Nullable<decimal> _ORDWTH;
		
		private string _COLOR_UP_CD;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOLDCOILNOChanging(string value);
    partial void OnCOLDCOILNOChanged();
    partial void OnORDTHKChanging(System.Nullable<decimal> value);
    partial void OnORDTHKChanged();
    partial void OnORDWTHChanging(System.Nullable<decimal> value);
    partial void OnORDWTHChanged();
    partial void OnCOLOR_UP_CDChanging(string value);
    partial void OnCOLOR_UP_CDChanged();
    #endregion
		
		public ERP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLDCOILNO", DbType="Char(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COLDCOILNO
		{
			get
			{
				return this._COLDCOILNO;
			}
			set
			{
				if ((this._COLDCOILNO != value))
				{
					this.OnCOLDCOILNOChanging(value);
					this.SendPropertyChanging();
					this._COLDCOILNO = value;
					this.SendPropertyChanged("COLDCOILNO");
					this.OnCOLDCOILNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDTHK", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> ORDTHK
		{
			get
			{
				return this._ORDTHK;
			}
			set
			{
				if ((this._ORDTHK != value))
				{
					this.OnORDTHKChanging(value);
					this.SendPropertyChanging();
					this._ORDTHK = value;
					this.SendPropertyChanged("ORDTHK");
					this.OnORDTHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDWTH", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> ORDWTH
		{
			get
			{
				return this._ORDWTH;
			}
			set
			{
				if ((this._ORDWTH != value))
				{
					this.OnORDWTHChanging(value);
					this.SendPropertyChanging();
					this._ORDWTH = value;
					this.SendPropertyChanged("ORDWTH");
					this.OnORDWTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR_UP_CD", DbType="Char(12)")]
		public string COLOR_UP_CD
		{
			get
			{
				return this._COLOR_UP_CD;
			}
			set
			{
				if ((this._COLOR_UP_CD != value))
				{
					this.OnCOLOR_UP_CDChanging(value);
					this.SendPropertyChanging();
					this._COLOR_UP_CD = value;
					this.SendPropertyChanged("COLOR_UP_CD");
					this.OnCOLOR_UP_CDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parameter")]
	public partial class Parameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HeadDistance;
		
		private string _HanFengDistance;
		
		private string _OperateDistance;
		
		private string _DirveDistance;
		
		private string _OperaPorportion;
		
		private string _DirverPorportion;
		
		private System.Nullable<System.DateTime> _SechayiScanTime;
		
		private string _Sechayi_timeLength;
		
		private string _Sechayi_leftDev;
		
		private string _Sechayi_RightDev;
		
		private string _Sechayi_Eloutu;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHeadDistanceChanging(string value);
    partial void OnHeadDistanceChanged();
    partial void OnHanFengDistanceChanging(string value);
    partial void OnHanFengDistanceChanged();
    partial void OnOperateDistanceChanging(string value);
    partial void OnOperateDistanceChanged();
    partial void OnDirveDistanceChanging(string value);
    partial void OnDirveDistanceChanged();
    partial void OnOperaPorportionChanging(string value);
    partial void OnOperaPorportionChanged();
    partial void OnDirverPorportionChanging(string value);
    partial void OnDirverPorportionChanged();
    partial void OnSechayiScanTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSechayiScanTimeChanged();
    partial void OnSechayi_timeLengthChanging(string value);
    partial void OnSechayi_timeLengthChanged();
    partial void OnSechayi_leftDevChanging(string value);
    partial void OnSechayi_leftDevChanged();
    partial void OnSechayi_RightDevChanging(string value);
    partial void OnSechayi_RightDevChanged();
    partial void OnSechayi_EloutuChanging(string value);
    partial void OnSechayi_EloutuChanged();
    #endregion
		
		public Parameter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadDistance", DbType="NVarChar(50)")]
		public string HeadDistance
		{
			get
			{
				return this._HeadDistance;
			}
			set
			{
				if ((this._HeadDistance != value))
				{
					this.OnHeadDistanceChanging(value);
					this.SendPropertyChanging();
					this._HeadDistance = value;
					this.SendPropertyChanged("HeadDistance");
					this.OnHeadDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanFengDistance", DbType="NVarChar(50)")]
		public string HanFengDistance
		{
			get
			{
				return this._HanFengDistance;
			}
			set
			{
				if ((this._HanFengDistance != value))
				{
					this.OnHanFengDistanceChanging(value);
					this.SendPropertyChanging();
					this._HanFengDistance = value;
					this.SendPropertyChanged("HanFengDistance");
					this.OnHanFengDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperateDistance", DbType="NVarChar(50)")]
		public string OperateDistance
		{
			get
			{
				return this._OperateDistance;
			}
			set
			{
				if ((this._OperateDistance != value))
				{
					this.OnOperateDistanceChanging(value);
					this.SendPropertyChanging();
					this._OperateDistance = value;
					this.SendPropertyChanged("OperateDistance");
					this.OnOperateDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirveDistance", DbType="NVarChar(50)")]
		public string DirveDistance
		{
			get
			{
				return this._DirveDistance;
			}
			set
			{
				if ((this._DirveDistance != value))
				{
					this.OnDirveDistanceChanging(value);
					this.SendPropertyChanging();
					this._DirveDistance = value;
					this.SendPropertyChanged("DirveDistance");
					this.OnDirveDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperaPorportion", DbType="NVarChar(50)")]
		public string OperaPorportion
		{
			get
			{
				return this._OperaPorportion;
			}
			set
			{
				if ((this._OperaPorportion != value))
				{
					this.OnOperaPorportionChanging(value);
					this.SendPropertyChanging();
					this._OperaPorportion = value;
					this.SendPropertyChanged("OperaPorportion");
					this.OnOperaPorportionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirverPorportion", DbType="NVarChar(50)")]
		public string DirverPorportion
		{
			get
			{
				return this._DirverPorportion;
			}
			set
			{
				if ((this._DirverPorportion != value))
				{
					this.OnDirverPorportionChanging(value);
					this.SendPropertyChanging();
					this._DirverPorportion = value;
					this.SendPropertyChanged("DirverPorportion");
					this.OnDirverPorportionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SechayiScanTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SechayiScanTime
		{
			get
			{
				return this._SechayiScanTime;
			}
			set
			{
				if ((this._SechayiScanTime != value))
				{
					this.OnSechayiScanTimeChanging(value);
					this.SendPropertyChanging();
					this._SechayiScanTime = value;
					this.SendPropertyChanged("SechayiScanTime");
					this.OnSechayiScanTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sechayi_timeLength", DbType="VarChar(50)")]
		public string Sechayi_timeLength
		{
			get
			{
				return this._Sechayi_timeLength;
			}
			set
			{
				if ((this._Sechayi_timeLength != value))
				{
					this.OnSechayi_timeLengthChanging(value);
					this.SendPropertyChanging();
					this._Sechayi_timeLength = value;
					this.SendPropertyChanged("Sechayi_timeLength");
					this.OnSechayi_timeLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sechayi_leftDev", DbType="NVarChar(50)")]
		public string Sechayi_leftDev
		{
			get
			{
				return this._Sechayi_leftDev;
			}
			set
			{
				if ((this._Sechayi_leftDev != value))
				{
					this.OnSechayi_leftDevChanging(value);
					this.SendPropertyChanging();
					this._Sechayi_leftDev = value;
					this.SendPropertyChanged("Sechayi_leftDev");
					this.OnSechayi_leftDevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sechayi_RightDev", DbType="NVarChar(50)")]
		public string Sechayi_RightDev
		{
			get
			{
				return this._Sechayi_RightDev;
			}
			set
			{
				if ((this._Sechayi_RightDev != value))
				{
					this.OnSechayi_RightDevChanging(value);
					this.SendPropertyChanging();
					this._Sechayi_RightDev = value;
					this.SendPropertyChanged("Sechayi_RightDev");
					this.OnSechayi_RightDevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sechayi_Eloutu", DbType="NVarChar(50)")]
		public string Sechayi_Eloutu
		{
			get
			{
				return this._Sechayi_Eloutu;
			}
			set
			{
				if ((this._Sechayi_Eloutu != value))
				{
					this.OnSechayi_EloutuChanging(value);
					this.SendPropertyChanging();
					this._Sechayi_Eloutu = value;
					this.SendPropertyChanged("Sechayi_Eloutu");
					this.OnSechayi_EloutuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PassStd")]
	public partial class PassStd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ColorCode;
		
		private System.Nullable<float> _delt_L_std;
		
		private System.Nullable<float> _delt_a_std;
		
		private System.Nullable<float> _delt_b_std;
		
		private System.Nullable<float> _delt_E_std;
		
		private string _color_name;
		
		private string _total_coating_thickness;
		
		private string _pencil_hardnees;
		
		private string _gloss;
		
		private string _T_bending;
		
		private string _reverse_resistance;
		
		private string _solvent_resistance;
		
		private System.Nullable<float> _L_C;
		
		private System.Nullable<float> _a_C;
		
		private System.Nullable<float> _b_C;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnColorCodeChanging(string value);
    partial void OnColorCodeChanged();
    partial void Ondelt_L_stdChanging(System.Nullable<float> value);
    partial void Ondelt_L_stdChanged();
    partial void Ondelt_a_stdChanging(System.Nullable<float> value);
    partial void Ondelt_a_stdChanged();
    partial void Ondelt_b_stdChanging(System.Nullable<float> value);
    partial void Ondelt_b_stdChanged();
    partial void Ondelt_E_stdChanging(System.Nullable<float> value);
    partial void Ondelt_E_stdChanged();
    partial void Oncolor_nameChanging(string value);
    partial void Oncolor_nameChanged();
    partial void Ontotal_coating_thicknessChanging(string value);
    partial void Ontotal_coating_thicknessChanged();
    partial void Onpencil_hardneesChanging(string value);
    partial void Onpencil_hardneesChanged();
    partial void OnglossChanging(string value);
    partial void OnglossChanged();
    partial void OnT_bendingChanging(string value);
    partial void OnT_bendingChanged();
    partial void Onreverse_resistanceChanging(string value);
    partial void Onreverse_resistanceChanged();
    partial void Onsolvent_resistanceChanging(string value);
    partial void Onsolvent_resistanceChanged();
    partial void OnL_CChanging(System.Nullable<float> value);
    partial void OnL_CChanged();
    partial void Ona_CChanging(System.Nullable<float> value);
    partial void Ona_CChanged();
    partial void Onb_CChanging(System.Nullable<float> value);
    partial void Onb_CChanged();
    #endregion
		
		public PassStd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ColorCode
		{
			get
			{
				return this._ColorCode;
			}
			set
			{
				if ((this._ColorCode != value))
				{
					this.OnColorCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorCode = value;
					this.SendPropertyChanged("ColorCode");
					this.OnColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delt_L_std", DbType="Real")]
		public System.Nullable<float> delt_L_std
		{
			get
			{
				return this._delt_L_std;
			}
			set
			{
				if ((this._delt_L_std != value))
				{
					this.Ondelt_L_stdChanging(value);
					this.SendPropertyChanging();
					this._delt_L_std = value;
					this.SendPropertyChanged("delt_L_std");
					this.Ondelt_L_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delt_a_std", DbType="Real")]
		public System.Nullable<float> delt_a_std
		{
			get
			{
				return this._delt_a_std;
			}
			set
			{
				if ((this._delt_a_std != value))
				{
					this.Ondelt_a_stdChanging(value);
					this.SendPropertyChanging();
					this._delt_a_std = value;
					this.SendPropertyChanged("delt_a_std");
					this.Ondelt_a_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delt_b_std", DbType="Real")]
		public System.Nullable<float> delt_b_std
		{
			get
			{
				return this._delt_b_std;
			}
			set
			{
				if ((this._delt_b_std != value))
				{
					this.Ondelt_b_stdChanging(value);
					this.SendPropertyChanging();
					this._delt_b_std = value;
					this.SendPropertyChanged("delt_b_std");
					this.Ondelt_b_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delt_E_std", DbType="Real")]
		public System.Nullable<float> delt_E_std
		{
			get
			{
				return this._delt_E_std;
			}
			set
			{
				if ((this._delt_E_std != value))
				{
					this.Ondelt_E_stdChanging(value);
					this.SendPropertyChanging();
					this._delt_E_std = value;
					this.SendPropertyChanged("delt_E_std");
					this.Ondelt_E_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NChar(40)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this.Oncolor_nameChanging(value);
					this.SendPropertyChanging();
					this._color_name = value;
					this.SendPropertyChanged("color_name");
					this.Oncolor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_coating_thickness", DbType="NChar(20)")]
		public string total_coating_thickness
		{
			get
			{
				return this._total_coating_thickness;
			}
			set
			{
				if ((this._total_coating_thickness != value))
				{
					this.Ontotal_coating_thicknessChanging(value);
					this.SendPropertyChanging();
					this._total_coating_thickness = value;
					this.SendPropertyChanged("total_coating_thickness");
					this.Ontotal_coating_thicknessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pencil_hardnees", DbType="NChar(20)")]
		public string pencil_hardnees
		{
			get
			{
				return this._pencil_hardnees;
			}
			set
			{
				if ((this._pencil_hardnees != value))
				{
					this.Onpencil_hardneesChanging(value);
					this.SendPropertyChanging();
					this._pencil_hardnees = value;
					this.SendPropertyChanged("pencil_hardnees");
					this.Onpencil_hardneesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloss", DbType="NChar(20)")]
		public string gloss
		{
			get
			{
				return this._gloss;
			}
			set
			{
				if ((this._gloss != value))
				{
					this.OnglossChanging(value);
					this.SendPropertyChanging();
					this._gloss = value;
					this.SendPropertyChanged("gloss");
					this.OnglossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_bending", DbType="NChar(20)")]
		public string T_bending
		{
			get
			{
				return this._T_bending;
			}
			set
			{
				if ((this._T_bending != value))
				{
					this.OnT_bendingChanging(value);
					this.SendPropertyChanging();
					this._T_bending = value;
					this.SendPropertyChanged("T_bending");
					this.OnT_bendingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reverse_resistance", DbType="NChar(20)")]
		public string reverse_resistance
		{
			get
			{
				return this._reverse_resistance;
			}
			set
			{
				if ((this._reverse_resistance != value))
				{
					this.Onreverse_resistanceChanging(value);
					this.SendPropertyChanging();
					this._reverse_resistance = value;
					this.SendPropertyChanged("reverse_resistance");
					this.Onreverse_resistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solvent_resistance", DbType="NChar(20)")]
		public string solvent_resistance
		{
			get
			{
				return this._solvent_resistance;
			}
			set
			{
				if ((this._solvent_resistance != value))
				{
					this.Onsolvent_resistanceChanging(value);
					this.SendPropertyChanging();
					this._solvent_resistance = value;
					this.SendPropertyChanged("solvent_resistance");
					this.Onsolvent_resistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_C", DbType="Real")]
		public System.Nullable<float> L_C
		{
			get
			{
				return this._L_C;
			}
			set
			{
				if ((this._L_C != value))
				{
					this.OnL_CChanging(value);
					this.SendPropertyChanging();
					this._L_C = value;
					this.SendPropertyChanged("L_C");
					this.OnL_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_C", DbType="Real")]
		public System.Nullable<float> a_C
		{
			get
			{
				return this._a_C;
			}
			set
			{
				if ((this._a_C != value))
				{
					this.Ona_CChanging(value);
					this.SendPropertyChanging();
					this._a_C = value;
					this.SendPropertyChanged("a_C");
					this.Ona_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_C", DbType="Real")]
		public System.Nullable<float> b_C
		{
			get
			{
				return this._b_C;
			}
			set
			{
				if ((this._b_C != value))
				{
					this.Onb_CChanging(value);
					this.SendPropertyChanging();
					this._b_C = value;
					this.SendPropertyChanged("b_C");
					this.Onb_CChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealTimeProduction")]
	public partial class RealTimeProduction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GUID;
		
		private System.DateTime _ProductTime;
		
		private string _RollNumber;
		
		private string _SubRollNumber;
		
		private float _ORDWTH;
		
		private string _ColorCode;
		
		private string _Flag;
		
		private float _LengthLocation;
		
		private float _WidthLocation;
		
		private float _RealTimeL;
		
		private float _RealTimeA;
		
		private float _RealTimeB;
		
		private float _RealTimeHeight;
		
		private float _StandardL;
		
		private float _StandardA;
		
		private float _StandardB;
		
		private float _DeltaL;
		
		private float _DeltaA;
		
		private float _DeltaB;
		
		private float _DeltaE;
		
		private float _DeltaL_Std;
		
		private float _DeltaA_Std;
		
		private float _DeltaB_Std;
		
		private float _DeltaE_Std;
		
		private bool _DeltaL_Warning;
		
		private bool _DeltaA_Warning;
		
		private bool _DeltaB_Warning;
		
		private bool _DeltaE_Warning;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGUIDChanging(System.Guid value);
    partial void OnGUIDChanged();
    partial void OnProductTimeChanging(System.DateTime value);
    partial void OnProductTimeChanged();
    partial void OnRollNumberChanging(string value);
    partial void OnRollNumberChanged();
    partial void OnSubRollNumberChanging(string value);
    partial void OnSubRollNumberChanged();
    partial void OnORDWTHChanging(float value);
    partial void OnORDWTHChanged();
    partial void OnColorCodeChanging(string value);
    partial void OnColorCodeChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnLengthLocationChanging(float value);
    partial void OnLengthLocationChanged();
    partial void OnWidthLocationChanging(float value);
    partial void OnWidthLocationChanged();
    partial void OnRealTimeLChanging(float value);
    partial void OnRealTimeLChanged();
    partial void OnRealTimeAChanging(float value);
    partial void OnRealTimeAChanged();
    partial void OnRealTimeBChanging(float value);
    partial void OnRealTimeBChanged();
    partial void OnRealTimeHeightChanging(float value);
    partial void OnRealTimeHeightChanged();
    partial void OnStandardLChanging(float value);
    partial void OnStandardLChanged();
    partial void OnStandardAChanging(float value);
    partial void OnStandardAChanged();
    partial void OnStandardBChanging(float value);
    partial void OnStandardBChanged();
    partial void OnDeltaLChanging(float value);
    partial void OnDeltaLChanged();
    partial void OnDeltaAChanging(float value);
    partial void OnDeltaAChanged();
    partial void OnDeltaBChanging(float value);
    partial void OnDeltaBChanged();
    partial void OnDeltaEChanging(float value);
    partial void OnDeltaEChanged();
    partial void OnDeltaL_StdChanging(float value);
    partial void OnDeltaL_StdChanged();
    partial void OnDeltaA_StdChanging(float value);
    partial void OnDeltaA_StdChanged();
    partial void OnDeltaB_StdChanging(float value);
    partial void OnDeltaB_StdChanged();
    partial void OnDeltaE_StdChanging(float value);
    partial void OnDeltaE_StdChanged();
    partial void OnDeltaL_WarningChanging(bool value);
    partial void OnDeltaL_WarningChanged();
    partial void OnDeltaA_WarningChanging(bool value);
    partial void OnDeltaA_WarningChanged();
    partial void OnDeltaB_WarningChanging(bool value);
    partial void OnDeltaB_WarningChanged();
    partial void OnDeltaE_WarningChanging(bool value);
    partial void OnDeltaE_WarningChanged();
    #endregion
		
		public RealTimeProduction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTime", DbType="DateTime NOT NULL")]
		public System.DateTime ProductTime
		{
			get
			{
				return this._ProductTime;
			}
			set
			{
				if ((this._ProductTime != value))
				{
					this.OnProductTimeChanging(value);
					this.SendPropertyChanging();
					this._ProductTime = value;
					this.SendPropertyChanged("ProductTime");
					this.OnProductTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RollNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RollNumber
		{
			get
			{
				return this._RollNumber;
			}
			set
			{
				if ((this._RollNumber != value))
				{
					this.OnRollNumberChanging(value);
					this.SendPropertyChanging();
					this._RollNumber = value;
					this.SendPropertyChanged("RollNumber");
					this.OnRollNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRollNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SubRollNumber
		{
			get
			{
				return this._SubRollNumber;
			}
			set
			{
				if ((this._SubRollNumber != value))
				{
					this.OnSubRollNumberChanging(value);
					this.SendPropertyChanging();
					this._SubRollNumber = value;
					this.SendPropertyChanged("SubRollNumber");
					this.OnSubRollNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDWTH", DbType="Real NOT NULL")]
		public float ORDWTH
		{
			get
			{
				return this._ORDWTH;
			}
			set
			{
				if ((this._ORDWTH != value))
				{
					this.OnORDWTHChanging(value);
					this.SendPropertyChanging();
					this._ORDWTH = value;
					this.SendPropertyChanged("ORDWTH");
					this.OnORDWTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ColorCode
		{
			get
			{
				return this._ColorCode;
			}
			set
			{
				if ((this._ColorCode != value))
				{
					this.OnColorCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorCode = value;
					this.SendPropertyChanged("ColorCode");
					this.OnColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LengthLocation", DbType="Real NOT NULL")]
		public float LengthLocation
		{
			get
			{
				return this._LengthLocation;
			}
			set
			{
				if ((this._LengthLocation != value))
				{
					this.OnLengthLocationChanging(value);
					this.SendPropertyChanging();
					this._LengthLocation = value;
					this.SendPropertyChanged("LengthLocation");
					this.OnLengthLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidthLocation", DbType="Real NOT NULL")]
		public float WidthLocation
		{
			get
			{
				return this._WidthLocation;
			}
			set
			{
				if ((this._WidthLocation != value))
				{
					this.OnWidthLocationChanging(value);
					this.SendPropertyChanging();
					this._WidthLocation = value;
					this.SendPropertyChanged("WidthLocation");
					this.OnWidthLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealTimeL", DbType="Real NOT NULL")]
		public float RealTimeL
		{
			get
			{
				return this._RealTimeL;
			}
			set
			{
				if ((this._RealTimeL != value))
				{
					this.OnRealTimeLChanging(value);
					this.SendPropertyChanging();
					this._RealTimeL = value;
					this.SendPropertyChanged("RealTimeL");
					this.OnRealTimeLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealTimeA", DbType="Real NOT NULL")]
		public float RealTimeA
		{
			get
			{
				return this._RealTimeA;
			}
			set
			{
				if ((this._RealTimeA != value))
				{
					this.OnRealTimeAChanging(value);
					this.SendPropertyChanging();
					this._RealTimeA = value;
					this.SendPropertyChanged("RealTimeA");
					this.OnRealTimeAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealTimeB", DbType="Real NOT NULL")]
		public float RealTimeB
		{
			get
			{
				return this._RealTimeB;
			}
			set
			{
				if ((this._RealTimeB != value))
				{
					this.OnRealTimeBChanging(value);
					this.SendPropertyChanging();
					this._RealTimeB = value;
					this.SendPropertyChanged("RealTimeB");
					this.OnRealTimeBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealTimeHeight", DbType="Real NOT NULL")]
		public float RealTimeHeight
		{
			get
			{
				return this._RealTimeHeight;
			}
			set
			{
				if ((this._RealTimeHeight != value))
				{
					this.OnRealTimeHeightChanging(value);
					this.SendPropertyChanging();
					this._RealTimeHeight = value;
					this.SendPropertyChanged("RealTimeHeight");
					this.OnRealTimeHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardL", DbType="Real NOT NULL")]
		public float StandardL
		{
			get
			{
				return this._StandardL;
			}
			set
			{
				if ((this._StandardL != value))
				{
					this.OnStandardLChanging(value);
					this.SendPropertyChanging();
					this._StandardL = value;
					this.SendPropertyChanged("StandardL");
					this.OnStandardLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardA", DbType="Real NOT NULL")]
		public float StandardA
		{
			get
			{
				return this._StandardA;
			}
			set
			{
				if ((this._StandardA != value))
				{
					this.OnStandardAChanging(value);
					this.SendPropertyChanging();
					this._StandardA = value;
					this.SendPropertyChanged("StandardA");
					this.OnStandardAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardB", DbType="Real NOT NULL")]
		public float StandardB
		{
			get
			{
				return this._StandardB;
			}
			set
			{
				if ((this._StandardB != value))
				{
					this.OnStandardBChanging(value);
					this.SendPropertyChanging();
					this._StandardB = value;
					this.SendPropertyChanged("StandardB");
					this.OnStandardBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaL", DbType="Real NOT NULL")]
		public float DeltaL
		{
			get
			{
				return this._DeltaL;
			}
			set
			{
				if ((this._DeltaL != value))
				{
					this.OnDeltaLChanging(value);
					this.SendPropertyChanging();
					this._DeltaL = value;
					this.SendPropertyChanged("DeltaL");
					this.OnDeltaLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaA", DbType="Real NOT NULL")]
		public float DeltaA
		{
			get
			{
				return this._DeltaA;
			}
			set
			{
				if ((this._DeltaA != value))
				{
					this.OnDeltaAChanging(value);
					this.SendPropertyChanging();
					this._DeltaA = value;
					this.SendPropertyChanged("DeltaA");
					this.OnDeltaAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaB", DbType="Real NOT NULL")]
		public float DeltaB
		{
			get
			{
				return this._DeltaB;
			}
			set
			{
				if ((this._DeltaB != value))
				{
					this.OnDeltaBChanging(value);
					this.SendPropertyChanging();
					this._DeltaB = value;
					this.SendPropertyChanged("DeltaB");
					this.OnDeltaBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaE", DbType="Real NOT NULL")]
		public float DeltaE
		{
			get
			{
				return this._DeltaE;
			}
			set
			{
				if ((this._DeltaE != value))
				{
					this.OnDeltaEChanging(value);
					this.SendPropertyChanging();
					this._DeltaE = value;
					this.SendPropertyChanged("DeltaE");
					this.OnDeltaEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaL_Std", DbType="Real NOT NULL")]
		public float DeltaL_Std
		{
			get
			{
				return this._DeltaL_Std;
			}
			set
			{
				if ((this._DeltaL_Std != value))
				{
					this.OnDeltaL_StdChanging(value);
					this.SendPropertyChanging();
					this._DeltaL_Std = value;
					this.SendPropertyChanged("DeltaL_Std");
					this.OnDeltaL_StdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaA_Std", DbType="Real NOT NULL")]
		public float DeltaA_Std
		{
			get
			{
				return this._DeltaA_Std;
			}
			set
			{
				if ((this._DeltaA_Std != value))
				{
					this.OnDeltaA_StdChanging(value);
					this.SendPropertyChanging();
					this._DeltaA_Std = value;
					this.SendPropertyChanged("DeltaA_Std");
					this.OnDeltaA_StdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaB_Std", DbType="Real NOT NULL")]
		public float DeltaB_Std
		{
			get
			{
				return this._DeltaB_Std;
			}
			set
			{
				if ((this._DeltaB_Std != value))
				{
					this.OnDeltaB_StdChanging(value);
					this.SendPropertyChanging();
					this._DeltaB_Std = value;
					this.SendPropertyChanged("DeltaB_Std");
					this.OnDeltaB_StdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaE_Std", DbType="Real NOT NULL")]
		public float DeltaE_Std
		{
			get
			{
				return this._DeltaE_Std;
			}
			set
			{
				if ((this._DeltaE_Std != value))
				{
					this.OnDeltaE_StdChanging(value);
					this.SendPropertyChanging();
					this._DeltaE_Std = value;
					this.SendPropertyChanged("DeltaE_Std");
					this.OnDeltaE_StdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaL_Warning", DbType="Bit NOT NULL")]
		public bool DeltaL_Warning
		{
			get
			{
				return this._DeltaL_Warning;
			}
			set
			{
				if ((this._DeltaL_Warning != value))
				{
					this.OnDeltaL_WarningChanging(value);
					this.SendPropertyChanging();
					this._DeltaL_Warning = value;
					this.SendPropertyChanged("DeltaL_Warning");
					this.OnDeltaL_WarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaA_Warning", DbType="Bit NOT NULL")]
		public bool DeltaA_Warning
		{
			get
			{
				return this._DeltaA_Warning;
			}
			set
			{
				if ((this._DeltaA_Warning != value))
				{
					this.OnDeltaA_WarningChanging(value);
					this.SendPropertyChanging();
					this._DeltaA_Warning = value;
					this.SendPropertyChanged("DeltaA_Warning");
					this.OnDeltaA_WarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaB_Warning", DbType="Bit NOT NULL")]
		public bool DeltaB_Warning
		{
			get
			{
				return this._DeltaB_Warning;
			}
			set
			{
				if ((this._DeltaB_Warning != value))
				{
					this.OnDeltaB_WarningChanging(value);
					this.SendPropertyChanging();
					this._DeltaB_Warning = value;
					this.SendPropertyChanged("DeltaB_Warning");
					this.OnDeltaB_WarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaE_Warning", DbType="Bit NOT NULL")]
		public bool DeltaE_Warning
		{
			get
			{
				return this._DeltaE_Warning;
			}
			set
			{
				if ((this._DeltaE_Warning != value))
				{
					this.OnDeltaE_WarningChanging(value);
					this.SendPropertyChanging();
					this._DeltaE_Warning = value;
					this.SendPropertyChanged("DeltaE_Warning");
					this.OnDeltaE_WarningChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _userId;
		
		private string _userName;
		
		private string _password;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(System.Guid value);
    partial void OnuserIdChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatisticsProduction")]
	public partial class StatisticsProduction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GUID;
		
		private System.Nullable<System.DateTime> _ProductTime;
		
		private string _RollNumber;
		
		private string _ColorCode;
		
		private float _DeltaL_Mean;
		
		private float _DeltaA_Mean;
		
		private float _DeltaB_Mean;
		
		private float _DeltaE_Mean;
		
		private float _DeltaL_MSE;
		
		private float _DeltaA_MSE;
		
		private float _DeltaB_MSE;
		
		private float _DeltaE_MSE;
		
		private float _flag;
		
		private int _GoodNumber;
		
		private int _BadNumber;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGUIDChanging(System.Guid value);
    partial void OnGUIDChanged();
    partial void OnProductTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnProductTimeChanged();
    partial void OnRollNumberChanging(string value);
    partial void OnRollNumberChanged();
    partial void OnColorCodeChanging(string value);
    partial void OnColorCodeChanged();
    partial void OnDeltaL_MeanChanging(float value);
    partial void OnDeltaL_MeanChanged();
    partial void OnDeltaA_MeanChanging(float value);
    partial void OnDeltaA_MeanChanged();
    partial void OnDeltaB_MeanChanging(float value);
    partial void OnDeltaB_MeanChanged();
    partial void OnDeltaE_MeanChanging(float value);
    partial void OnDeltaE_MeanChanged();
    partial void OnDeltaL_MSEChanging(float value);
    partial void OnDeltaL_MSEChanged();
    partial void OnDeltaA_MSEChanging(float value);
    partial void OnDeltaA_MSEChanged();
    partial void OnDeltaB_MSEChanging(float value);
    partial void OnDeltaB_MSEChanged();
    partial void OnDeltaE_MSEChanging(float value);
    partial void OnDeltaE_MSEChanged();
    partial void OnflagChanging(float value);
    partial void OnflagChanged();
    partial void OnGoodNumberChanging(int value);
    partial void OnGoodNumberChanged();
    partial void OnBadNumberChanging(int value);
    partial void OnBadNumberChanged();
    #endregion
		
		public StatisticsProduction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProductTime
		{
			get
			{
				return this._ProductTime;
			}
			set
			{
				if ((this._ProductTime != value))
				{
					this.OnProductTimeChanging(value);
					this.SendPropertyChanging();
					this._ProductTime = value;
					this.SendPropertyChanged("ProductTime");
					this.OnProductTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RollNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RollNumber
		{
			get
			{
				return this._RollNumber;
			}
			set
			{
				if ((this._RollNumber != value))
				{
					this.OnRollNumberChanging(value);
					this.SendPropertyChanging();
					this._RollNumber = value;
					this.SendPropertyChanged("RollNumber");
					this.OnRollNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ColorCode
		{
			get
			{
				return this._ColorCode;
			}
			set
			{
				if ((this._ColorCode != value))
				{
					this.OnColorCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorCode = value;
					this.SendPropertyChanged("ColorCode");
					this.OnColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaL_Mean", DbType="Real NOT NULL")]
		public float DeltaL_Mean
		{
			get
			{
				return this._DeltaL_Mean;
			}
			set
			{
				if ((this._DeltaL_Mean != value))
				{
					this.OnDeltaL_MeanChanging(value);
					this.SendPropertyChanging();
					this._DeltaL_Mean = value;
					this.SendPropertyChanged("DeltaL_Mean");
					this.OnDeltaL_MeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaA_Mean", DbType="Real NOT NULL")]
		public float DeltaA_Mean
		{
			get
			{
				return this._DeltaA_Mean;
			}
			set
			{
				if ((this._DeltaA_Mean != value))
				{
					this.OnDeltaA_MeanChanging(value);
					this.SendPropertyChanging();
					this._DeltaA_Mean = value;
					this.SendPropertyChanged("DeltaA_Mean");
					this.OnDeltaA_MeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaB_Mean", DbType="Real NOT NULL")]
		public float DeltaB_Mean
		{
			get
			{
				return this._DeltaB_Mean;
			}
			set
			{
				if ((this._DeltaB_Mean != value))
				{
					this.OnDeltaB_MeanChanging(value);
					this.SendPropertyChanging();
					this._DeltaB_Mean = value;
					this.SendPropertyChanged("DeltaB_Mean");
					this.OnDeltaB_MeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaE_Mean", DbType="Real NOT NULL")]
		public float DeltaE_Mean
		{
			get
			{
				return this._DeltaE_Mean;
			}
			set
			{
				if ((this._DeltaE_Mean != value))
				{
					this.OnDeltaE_MeanChanging(value);
					this.SendPropertyChanging();
					this._DeltaE_Mean = value;
					this.SendPropertyChanged("DeltaE_Mean");
					this.OnDeltaE_MeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaL_MSE", DbType="Real NOT NULL")]
		public float DeltaL_MSE
		{
			get
			{
				return this._DeltaL_MSE;
			}
			set
			{
				if ((this._DeltaL_MSE != value))
				{
					this.OnDeltaL_MSEChanging(value);
					this.SendPropertyChanging();
					this._DeltaL_MSE = value;
					this.SendPropertyChanged("DeltaL_MSE");
					this.OnDeltaL_MSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaA_MSE", DbType="Real NOT NULL")]
		public float DeltaA_MSE
		{
			get
			{
				return this._DeltaA_MSE;
			}
			set
			{
				if ((this._DeltaA_MSE != value))
				{
					this.OnDeltaA_MSEChanging(value);
					this.SendPropertyChanging();
					this._DeltaA_MSE = value;
					this.SendPropertyChanged("DeltaA_MSE");
					this.OnDeltaA_MSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaB_MSE", DbType="Real NOT NULL")]
		public float DeltaB_MSE
		{
			get
			{
				return this._DeltaB_MSE;
			}
			set
			{
				if ((this._DeltaB_MSE != value))
				{
					this.OnDeltaB_MSEChanging(value);
					this.SendPropertyChanging();
					this._DeltaB_MSE = value;
					this.SendPropertyChanged("DeltaB_MSE");
					this.OnDeltaB_MSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaE_MSE", DbType="Real NOT NULL")]
		public float DeltaE_MSE
		{
			get
			{
				return this._DeltaE_MSE;
			}
			set
			{
				if ((this._DeltaE_MSE != value))
				{
					this.OnDeltaE_MSEChanging(value);
					this.SendPropertyChanging();
					this._DeltaE_MSE = value;
					this.SendPropertyChanged("DeltaE_MSE");
					this.OnDeltaE_MSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Real NOT NULL")]
		public float flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this.OnflagChanging(value);
					this.SendPropertyChanging();
					this._flag = value;
					this.SendPropertyChanged("flag");
					this.OnflagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodNumber", DbType="Int NOT NULL")]
		public int GoodNumber
		{
			get
			{
				return this._GoodNumber;
			}
			set
			{
				if ((this._GoodNumber != value))
				{
					this.OnGoodNumberChanging(value);
					this.SendPropertyChanging();
					this._GoodNumber = value;
					this.SendPropertyChanged("GoodNumber");
					this.OnGoodNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadNumber", DbType="Int NOT NULL")]
		public int BadNumber
		{
			get
			{
				return this._BadNumber;
			}
			set
			{
				if ((this._BadNumber != value))
				{
					this.OnBadNumberChanging(value);
					this.SendPropertyChanging();
					this._BadNumber = value;
					this.SendPropertyChanged("BadNumber");
					this.OnBadNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
